### ISSUE TITLE
heroku No web processes running

### ISSUE THREAD

**Issue by chrishough** [bolderbrooklyn/jbhannah.net-jekyll#19]
I have followed a few guides and I am truly thankful for your post, however,I keep running into the error `No web processes running` when trying to get my blog up and running.  Any ideas on how to fix this?

**Comment by bolderbrooklyn** [comment]
Make sure you have a Procfile with a web process that starts the server.

**Comment by chrishough** [comment]
Here is what I am using... Ideas?

config.ru

```
require 'rack/contrib/try_static'
require 'rack/contrib/not_found'
require 'rack/rewrite'

use Rack::TryStatic,
  urls: %w[/],
  root: "_site",
  try: ['index.html', '/index.html'],
  header_rules: [
    [["html"],  {'Content-Type' => 'text/html; charset=utf-8'}],
    [["css"],   {'Content-Type' => 'text/css'}],
    [["js"],    {'Content-Type' => 'text/javascript'}],
    [["png"],   {'Content-Type' => 'image/png'}],
    ["/assets", {'Cache-Control' => 'public, max-age=31536000'}],
  ]

run Rack::NotFound.new('_site/404.html')

```

Gemfile

```
source 'https://rubygems.org'
ruby '2.0.0'
# ------------------------------------------------------------------------------------
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# ------------------------------------------------------------------------------------
gem 'rake'
gem 'jekyll'
gem "jekyll-assets"
gem "rack-contrib"
gem "rack-rewrite"
gem "puma"
gem "kramdown"
# ------------------------------------------------------------------------------------
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# ------------------------------------------------------------------------------------
group :production do
  gem "newrelic_rpm"
end
```

Procfile

```
web: bundle exec puma -p $PORT config.ru 3:5
```

Rakefile

```
namespace :assets do
  desc 'Precompile assets'
  task :precompile do
    sh "bundle exec jekyll build"
  end
end
```

**Comment by chrishough** [comment]
Which basically matches your setup?

**Comment by bolderbrooklyn** [comment]
Have you run `heroku log` to see if any error messages are coming up when Heroku builds the site and tries to start the server?

**Comment by chrishough** [comment]
I was able to get it running with this configuration:

config.ru

```
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require "bundler/setup"
Bundler.require(:default)

run Rack::Jekyll.new(:destination => '_site')
```

procfile

```
web: bundle exec puma -p $PORT -e $RACK_ENV -t 3:5
```

**Comment by bolderbrooklyn** [comment]
After taking a closer look I noticed the `3:5` at the end of the `web` line in the first version of your `Procfile`, while in the second version you have `-t 3:5`. I think the reason it wasn't working may have been that you were missing the `-t` flag (I don't specify a thread pool size in my `Procfile`).

**Comment by chrishough** [comment]
Interesting point, I had not noticed that.  I was able to get it working so I believe we can close this for now.  Have a great week.

**Comment by chrishough** [comment]
I just migrated to using S3 for full static hosting ::: ..

https://github.com/laurilehmijoki/s3_website
http://vvv.tobiassjosten.net/development/jekyll-blog-on-amazon-s3-and-cloudfront/
